export const CHECKLIST_LOAD_INDEX_START   = 'CHECKLIST_LOAD_INDEX_START'
export const CHECKLIST_LOAD_INDEX_SUCCESS = 'CHECKLIST_LOAD_INDEX_SUCCESS'
export const CHECKLIST_LOAD_INDEX_FAILED  = 'CHECKLIST_LOAD_INDEX_FAILED'
